theme = "dracula"

[editor]
color-modes = true
auto-pairs = false

[editor.cursor-shape]
#insert = "bar"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control", "read-only-indicator", "file-modification-indicator"]

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
